services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network

  pollapp.server:
    image: ${DOCKER_REGISTRY-}pollappserver
    build:
      context: .
      dockerfile: PollApp.Server/Dockerfile
